on:
  workflow_call:
    inputs:
      event_type:
        required: false
        type: string
        default: cd-deploy
      gh_user:
        required: true
        type: string
      gh_repo:
        required: true
        type: string
      image_name:
        required: true
        type: string
      env_name:
        required: true
        type: string
      app_path:
        required: true
        type: string
      auto_merge:
        required: true
        type: boolean
      pr_assignees:
        type: string
        required: false
        default: ""
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Extract TAG env
        run: |
          ref="${{ github.ref }}"
          echo "TAG=${ref/refs\/tags\//}" >> $GITHUB_ENV
      - name: Dispatch repo event
        run: |-
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -d '{
            "event_type": "${{ inputs.event_type }}",
            "client_payload": {
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "tag": "${{ env.TAG }}",
              "image_name": "${{ inputs.image_name }}",
              "image_tag": "${{ env.TAG }}",
              "env_name": "${{ inputs.env_name }}",
              "app_path": "${{ inputs.app_path }}",
              "auto_merge": ${{ inputs.auto_merge }},
              "pr_assignees": "${{ inputs.pr_assignees }}"
            }
          }' \
          https://api.github.com/repos/${{ inputs.gh_user }}/${{ inputs.gh_repo }}/dispatches
